name: pytask-examples

channels:
  - conda-forge
  - defaults

dependencies:
  - conda-build
  - python=3.9
  - pytask
  - pytask-latex
  - pytask-parallel
  - estimagic
  - pip
  - plotly
  - python-kaleido

  - pip:
      - black
      - pre-commit
      - pdbpp
